#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color        \#F5A5A5
bspc config window_gap          60
bspc config border_radius       8pm

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          20

~/.config/polybar/launch.sh &
picom --experimental-backend &
feh --bg-fill ~/.config/wallpapers/current.jpg &
wmname LG3D &
setxkbmap -v workman && xset r 66

